# Generated by Django 4.2.4 on 2024-05-30 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviaSales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 15, 55, 46, 791942, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 15, 55, 46, 791911, tzinfo=datetime.timezone.utc)),
        ),
    ]
