# Generated by Django 4.2.4 on 2024-05-30 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviaSales', '0003_alter_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_active',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 18, 27, 48, 12942, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 18, 27, 48, 12919, tzinfo=datetime.timezone.utc)),
        ),
    ]
